version = 1
graph = "implement-and-simplify.dot"

[sandbox]
provider = "local"
# provider = "daytona"

# [sandbox.env]
# CARGO_INCREMENTAL = "0"

# [sandbox.daytona.snapshot]
# name = "daytona-large"


[sandbox.local]
worktree = true