/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AggregateUsageTotals } from './aggregate-usage-totals';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageByModel } from './usage-by-model';

/**
 * Aggregate token and cost usage across all runs since server start.
 */
export interface AggregateUsage {
    'totals': AggregateUsageTotals;
    /**
     * Usage grouped by model.
     */
    'by_model': Array<UsageByModel>;
}

