/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Detailed information about a verification control including checks and examples.
 */
export interface ControlDetail {
    /**
     * Detailed prose description of the control\'s purpose and rationale.
     */
    'rationale': string;
    /**
     * Specific checks performed by this control.
     */
    'checks': Array<string>;
    /**
     * Example scenario where the control passes.
     */
    'pass_example': string;
    /**
     * Example scenario where the control fails.
     */
    'fail_example': string;
}

