/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for starting a new session.
 */
export interface CreateSessionRequest {
    /**
     * The initial user message to start the session.
     */
    'content': string;
    /**
     * LLM model to use. If omitted, the server default is used.
     */
    'model'?: string;
    /**
     * System prompt for the session.
     */
    'system'?: string;
}

