/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Snapshot configuration for Daytona sandboxes.
 */
export interface DaytonaSnapshotConfiguration {
    /**
     * Snapshot name.
     */
    'name': string;
    /**
     * CPU cores.
     */
    'cpu'?: number;
    /**
     * Memory in GB.
     */
    'memory'?: number;
    /**
     * Disk in GB.
     */
    'disk'?: number;
    /**
     * Dockerfile content for snapshot creation.
     */
    'dockerfile'?: string;
}

