/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GitAuthorConfiguration } from './git-author-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { WebhookConfiguration } from './webhook-configuration';

/**
 * Git provider configuration.
 */
export interface GitConfiguration {
    /**
     * Git provider.
     */
    'provider'?: GitConfigurationProviderEnum;
    /**
     * GitHub App ID.
     */
    'app_id'?: string;
    /**
     * GitHub App Client ID.
     */
    'client_id'?: string;
    /**
     * GitHub App slug.
     */
    'slug'?: string;
    'author'?: GitAuthorConfiguration;
    'webhooks'?: WebhookConfiguration;
}

export const GitConfigurationProviderEnum = {
    GITHUB: 'github'
} as const;

export type GitConfigurationProviderEnum = typeof GitConfigurationProviderEnum[keyof typeof GitConfigurationProviderEnum];


