/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OpenItemKind } from './open-item-kind';

/**
 * A follow-up item identified during the run.
 */
export interface OpenItem {
    'kind': OpenItemKind;
    /**
     * Description of the open item.
     */
    'description': string;
}



