/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of open item identified during a run.
 */

export const OpenItemKind = {
    TECH_DEBT: 'tech_debt',
    FOLLOW_UP: 'follow_up',
    INVESTIGATION: 'investigation',
    TEST_GAP: 'test_gap'
} as const;

export type OpenItemKind = typeof OpenItemKind[keyof typeof OpenItemKind];



