/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FrictionPoint } from './friction-point';
// May contain unused imports in some cases
// @ts-ignore
import type { Learning } from './learning';
// May contain unused imports in some cases
// @ts-ignore
import type { OpenItem } from './open-item';
// May contain unused imports in some cases
// @ts-ignore
import type { RetroStats } from './retro-stats';
// May contain unused imports in some cases
// @ts-ignore
import type { SmoothnessRating } from './smoothness-rating';
// May contain unused imports in some cases
// @ts-ignore
import type { StageRetro } from './stage-retro';

/**
 * Full retrospective analysis for a completed run.
 */
export interface RetroDetail {
    /**
     * Unique run identifier.
     */
    'run_id': string;
    /**
     * Workflow slug that produced this run.
     */
    'workflow_name': string;
    /**
     * The goal that was set for the run.
     */
    'goal': string;
    /**
     * ISO 8601 timestamp when the retro was generated.
     */
    'timestamp': string;
    /**
     * Absent when the retro has been generated from quantitative data but not yet enriched by the retro agent.
     */
    'smoothness'?: SmoothnessRating;
    /**
     * Per-stage retrospective data.
     */
    'stages': Array<StageRetro>;
    'stats': RetroStats;
    /**
     * What the agent intended to accomplish.
     */
    'intent'?: string;
    /**
     * What actually happened during the run.
     */
    'outcome'?: string;
    /**
     * Insights discovered during the run.
     */
    'learnings'?: Array<Learning>;
    /**
     * Points where the run encountered difficulty.
     */
    'friction_points'?: Array<FrictionPoint>;
    /**
     * Follow-up items identified during the run.
     */
    'open_items'?: Array<OpenItem>;
}



