/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StageStatus } from './stage-status';

/**
 * A single stage in a run\'s workflow graph.
 */
export interface RunStage {
    /**
     * Unique stage identifier within the run.
     */
    'id': string;
    /**
     * Human-readable stage name.
     */
    'name': string;
    'status': StageStatus;
    /**
     * Time spent in this stage, in seconds.
     */
    'duration_secs'?: number;
    /**
     * Node identifier in the DOT graph source.
     */
    'dot_id'?: string;
}



