/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssistantTurn } from './assistant-turn';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolTurn } from './tool-turn';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolUse } from './tool-use';
// May contain unused imports in some cases
// @ts-ignore
import type { UserTurn } from './user-turn';

/**
 * @type SessionTurn
 * A single turn in a session conversation — a user message, assistant response, or tool invocation block.
 */
export type SessionTurn = { kind: 'assistant' } & AssistantTurn | { kind: 'tool' } & ToolTurn | { kind: 'user' } & UserTurn;


