/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Retrospective data for a single stage in the workflow.
 */
export interface StageRetro {
    /**
     * Identifier of the stage in the workflow graph.
     */
    'stage_id': string;
    /**
     * Human-readable label for the stage.
     */
    'stage_label': string;
    /**
     * Final status of the stage.
     */
    'status': string;
    /**
     * Stage duration in milliseconds.
     */
    'duration_ms': number;
    /**
     * Number of retries for this stage.
     */
    'retries': number;
    /**
     * Cost in USD for this stage. Absent when cost data is unavailable.
     */
    'cost'?: number;
    /**
     * Optional notes about this stage\'s execution.
     */
    'notes'?: string;
    /**
     * Reason the stage failed, if applicable.
     */
    'failure_reason'?: string;
    /**
     * Files modified during this stage.
     */
    'files_touched': Array<string>;
}

