/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ToolUse } from './tool-use';

/**
 * A tool invocation turn containing one or more tool calls.
 */
export interface ToolStageTurn {
    'kind': ToolStageTurnKindEnum;
    /**
     * Text accompanying the tool invocations, or null when the turn contains only tool calls.
     */
    'content'?: string;
    /**
     * Tool invocations executed in this turn.
     */
    'tools': Array<ToolUse>;
}

export const ToolStageTurnKindEnum = {
    TOOL: 'tool'
} as const;

export type ToolStageTurnKindEnum = typeof ToolStageTurnKindEnum[keyof typeof ToolStageTurnKindEnum];


