/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Aggregate usage totals across all stages of a run.
 */
export interface UsageTotals {
    /**
     * Total wall-clock runtime in seconds.
     */
    'runtime_secs': number;
    /**
     * Total input tokens consumed.
     */
    'input_tokens': number;
    /**
     * Total output tokens generated.
     */
    'output_tokens': number;
    /**
     * Total cost in USD.
     */
    'cost': number;
}

