/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ControlDetail } from './control-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { ControlInfo } from './control-info';
// May contain unused imports in some cases
// @ts-ignore
import type { ControlPerformance } from './control-performance';
// May contain unused imports in some cases
// @ts-ignore
import type { RecentControlResult } from './recent-control-result';
// May contain unused imports in some cases
// @ts-ignore
import type { SiblingControl } from './sibling-control';

/**
 * Complete detail view of a verification control with performance, examples, and recent results.
 */
export interface VerificationDetailResponse {
    'control': ControlInfo;
    'performance': ControlPerformance;
    'control_detail': ControlDetail;
    /**
     * Recent evaluation results across runs.
     */
    'recent_results': Array<RecentControlResult>;
    /**
     * Other controls in the same category.
     */
    'siblings': Array<SiblingControl>;
}

