/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Schedule configuration for a workflow.
 */
export interface WorkflowSchedule {
    /**
     * Cron-like schedule expression.
     */
    'expression': string;
    /**
     * ISO 8601 timestamp of the next scheduled run.
     */
    'next_run'?: string;
}

