/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TlsConfiguration } from './tls-configuration';

/**
 * API server configuration.
 */
export interface ApiConfiguration {
    /**
     * API base URL.
     */
    'base_url'?: string;
    /**
     * Authentication strategies.
     */
    'authentication_strategies'?: Array<ApiConfigurationAuthenticationStrategiesEnum>;
    'tls'?: TlsConfiguration;
}

export const ApiConfigurationAuthenticationStrategiesEnum = {
    JWT: 'jwt',
    MTLS: 'mtls'
} as const;

export type ApiConfigurationAuthenticationStrategiesEnum = typeof ApiConfigurationAuthenticationStrategiesEnum[keyof typeof ApiConfigurationAuthenticationStrategiesEnum];


