/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Board column status for a run in the list view.
 */

export const BoardColumn = {
    WORKING: 'working',
    PENDING: 'pending',
    REVIEW: 'review',
    MERGE: 'merge'
} as const;

export type BoardColumn = typeof BoardColumn[keyof typeof BoardColumn];



