/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMode } from './verification-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationResult } from './verification-result';

/**
 * Performance metrics for a verification control.
 */
export interface ControlPerformance {
    'mode': VerificationMode;
    /**
     * F1 score of the control\'s AI evaluator.
     */
    'f1'?: number;
    /**
     * Pass@1 rate.
     */
    'pass_at_1'?: number;
    /**
     * Recent evaluation results (newest first).
     */
    'evaluations': Array<VerificationResult>;
}



