/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A file\'s contents at one side of a diff.
 */
export interface DiffFile {
    /**
     * File path relative to the repository root.
     */
    'name': string;
    /**
     * Full file contents. Empty string for newly created or deleted files.
     */
    'contents': string;
}

