/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of friction encountered during a run.
 */

export const FrictionKind = {
    RETRY: 'retry',
    TIMEOUT: 'timeout',
    WRONG_APPROACH: 'wrong_approach',
    TOOL_FAILURE: 'tool_failure',
    AMBIGUITY: 'ambiguity'
} as const;

export type FrictionKind = typeof FrictionKind[keyof typeof FrictionKind];



