/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelCosts } from './model-costs';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelFeatures } from './model-features';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelLimits } from './model-limits';

/**
 * An available LLM model from the built-in catalog.
 */
export interface Model {
    /**
     * Unique model identifier.
     */
    'id': string;
    /**
     * Provider that serves this model.
     */
    'provider': string;
    /**
     * Model family grouping.
     */
    'family': string;
    /**
     * Human-readable model name.
     */
    'display_name': string;
    'limits': ModelLimits;
    /**
     * Training data cutoff date (YYYY-MM-DD).
     */
    'training'?: string;
    'features': ModelFeatures;
    'costs': ModelCosts;
    /**
     * Estimated output tokens per second.
     */
    'estimated_output_tps'?: number;
    /**
     * Alternative names that resolve to this model.
     */
    'aliases': Array<string>;
    /**
     * Whether this is the default model for its provider.
     */
    'default': boolean;
}

