/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Capability flags for a model.
 */
export interface ModelFeatures {
    /**
     * Whether the model supports tool use.
     */
    'tools': boolean;
    /**
     * Whether the model supports vision/image inputs.
     */
    'vision': boolean;
    /**
     * Whether the model supports extended reasoning.
     */
    'reasoning': boolean;
}

