/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Summary statistics for a run retrospective.
 */
export interface RetroStats {
    /**
     * Total run duration in milliseconds.
     */
    'total_duration_ms': number;
    /**
     * Total cost in USD. Absent when cost data is unavailable from the model provider.
     */
    'total_cost'?: number;
    /**
     * Total number of retries across all stages.
     */
    'total_retries': number;
    /**
     * List of files modified during the run.
     */
    'files_touched': Array<string>;
    /**
     * Number of stages that completed successfully.
     */
    'stages_completed': number;
    /**
     * Number of stages that failed.
     */
    'stages_failed': number;
}

