/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunVerificationControl } from './run-verification-control';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationResult } from './verification-result';

/**
 * Verification results for a category within a run.
 */
export interface RunVerification {
    /**
     * Category name.
     */
    'name': string;
    /**
     * The guiding question for this verification category.
     */
    'question': string;
    'status': VerificationResult;
    /**
     * Individual control results within this category.
     */
    'controls': Array<RunVerificationControl>;
}



