/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UsageByModel } from './usage-by-model';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageStage } from './usage-stage';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageTotals } from './usage-totals';

/**
 * Complete usage breakdown for a single run.
 */
export interface RunUsage {
    /**
     * Per-stage usage breakdown.
     */
    'stages': Array<UsageStage>;
    'totals': UsageTotals;
    /**
     * Usage grouped by model.
     */
    'by_model': Array<UsageByModel>;
}

