/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiConfiguration } from './api-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { AssetsConfiguration } from './assets-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { CheckpointConfiguration } from './checkpoint-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { FeatureFlags } from './feature-flags';
// May contain unused imports in some cases
// @ts-ignore
import type { GitConfiguration } from './git-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { HookDefinition } from './hook-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { LlmConfiguration } from './llm-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { LogConfiguration } from './log-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestConfiguration } from './pull-request-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxConfiguration } from './sandbox-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { SetupConfiguration } from './setup-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { WebConfiguration } from './web-configuration';

/**
 * Structured server configuration mirroring ServerConfig.
 */
export interface ServerConfiguration {
    /**
     * Data directory path.
     */
    'data_dir'?: string;
    /**
     * Maximum concurrent runs.
     */
    'max_concurrent_runs'?: number;
    'web'?: WebConfiguration;
    'api'?: ApiConfiguration;
    'git'?: GitConfiguration;
    'feature_flags'?: FeatureFlags;
    'log'?: LogConfiguration;
    /**
     * Default working directory.
     */
    'directory'?: string;
    'llm'?: LlmConfiguration;
    'setup'?: SetupConfiguration;
    'sandbox'?: SandboxConfiguration;
    /**
     * Default variable map.
     */
    'vars'?: { [key: string]: string; };
    'checkpoint'?: CheckpointConfiguration;
    'pull_request'?: PullRequestConfiguration;
    'hooks'?: Array<HookDefinition>;
    'assets'?: AssetsConfiguration;
}

