/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMode } from './verification-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationType } from './verification-type';

/**
 * Summary of a sibling verification control in the same category.
 */
export interface SiblingControl {
    /**
     * Human-readable control name.
     */
    'name': string;
    /**
     * URL-safe slug.
     */
    'slug': string;
    'type'?: VerificationType;
    'mode'?: VerificationMode;
}



