/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssistantStageTurn } from './assistant-stage-turn';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemStageTurn } from './system-stage-turn';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolStageTurn } from './tool-stage-turn';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolUse } from './tool-use';

/**
 * @type StageTurn
 * A single turn in a stage conversation — a system prompt, assistant response, or tool invocation block.
 */
export type StageTurn = { kind: 'assistant' } & AssistantStageTurn | { kind: 'system' } & SystemStageTurn | { kind: 'tool' } & ToolStageTurn;


