/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A user message turn.
 */
export interface UserTurn {
    'kind': UserTurnKindEnum;
    /**
     * Text content of the user message.
     */
    'content': string;
    /**
     * Timestamp when the turn was created.
     */
    'created_at': string;
}

export const UserTurnKindEnum = {
    USER: 'user'
} as const;

export type UserTurnKindEnum = typeof UserTurnKindEnum[keyof typeof UserTurnKindEnum];


