/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunConfiguration } from './run-configuration';

/**
 * Full detail of a workflow definition including graph and configuration.
 */
export interface WorkflowDetail {
    /**
     * Human-readable workflow name.
     */
    'name': string;
    /**
     * URL-safe slug used in API paths.
     */
    'slug': string;
    /**
     * DOT graph filename.
     */
    'filename': string;
    /**
     * Prose description of what the workflow does.
     */
    'description': string;
    'config': RunConfiguration;
    /**
     * DOT language source defining the workflow graph.
     */
    'graph': string;
}

