/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An assistant response turn.
 */
export interface AssistantTurn {
    'kind': AssistantTurnKindEnum;
    /**
     * Text content of the assistant response.
     */
    'content': string;
    /**
     * Timestamp when the turn was created.
     */
    'created_at': string;
}

export const AssistantTurnKindEnum = {
    ASSISTANT: 'assistant'
} as const;

export type AssistantTurnKindEnum = typeof AssistantTurnKindEnum[keyof typeof AssistantTurnKindEnum];


