/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response returned after successfully creating a session.
 */
export interface CreateSessionResponse {
    /**
     * Unique identifier for the newly created session.
     */
    'id': string;
    /**
     * Server-generated title for the session.
     */
    'title': string;
    /**
     * The resolved LLM model for this session (may be the server default).
     */
    'model': string;
    /**
     * Timestamp when the session was created.
     */
    'created_at': string;
}

