/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Error event.
 */
export interface SessionEventError {
    'event': SessionEventErrorEventEnum;
    /**
     * Human-readable error message.
     */
    'message': string;
}

export const SessionEventErrorEventEnum = {
    ERROR: 'error'
} as const;

export type SessionEventErrorEventEnum = typeof SessionEventErrorEventEnum[keyof typeof SessionEventErrorEventEnum];


