/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stream completion event.
 */
export interface SessionEventDone {
    'event': SessionEventDoneEventEnum;
}

export const SessionEventDoneEventEnum = {
    DONE: 'done'
} as const;

export type SessionEventDoneEventEnum = typeof SessionEventDoneEventEnum[keyof typeof SessionEventDoneEventEnum];


