/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionEventAssistantTurn } from './session-event-assistant-turn';
// May contain unused imports in some cases
// @ts-ignore
import type { SessionEventDone } from './session-event-done';
// May contain unused imports in some cases
// @ts-ignore
import type { SessionEventError } from './session-event-error';
// May contain unused imports in some cases
// @ts-ignore
import type { SessionEventToolTurn } from './session-event-tool-turn';
// May contain unused imports in some cases
// @ts-ignore
import type { ToolTurn } from './tool-turn';

/**
 * @type SessionEvent
 * Discriminated union of all SSE event payloads.
 */
export type SessionEvent = { event: 'assistant_turn' } & SessionEventAssistantTurn | { event: 'done' } & SessionEventDone | { event: 'error' } & SessionEventError | { event: 'tool_turn' } & SessionEventToolTurn;


