/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssistantTurn } from './assistant-turn';

/**
 * An assistant turn event.
 */
export interface SessionEventAssistantTurn {
    'event': SessionEventAssistantTurnEventEnum;
    'data': AssistantTurn;
}

export const SessionEventAssistantTurnEventEnum = {
    ASSISTANT_TURN: 'assistant_turn'
} as const;

export type SessionEventAssistantTurnEventEnum = typeof SessionEventAssistantTurnEventEnum[keyof typeof SessionEventAssistantTurnEventEnum];


