/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ToolUse } from './tool-use';

/**
 * A tool invocation turn.
 */
export interface ToolTurn {
    'kind': ToolTurnKindEnum;
    /**
     * Tool invocations for this turn.
     */
    'tools': Array<ToolUse>;
    /**
     * Timestamp when the turn was created.
     */
    'created_at': string;
}

export const ToolTurnKindEnum = {
    TOOL: 'tool'
} as const;

export type ToolTurnKindEnum = typeof ToolTurnKindEnum[keyof typeof ToolTurnKindEnum];


